<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CFDBD86" ignored="9" name="FirefoxTest" tests="13" failures="8" timestamp="02 Sep 2019 13:59:19 GMT" time="602.963" errors="0">
  <testcase name="sanityTest" time="63.518" classname="tests.SanityTest"/>
  <testcase name="QinAnotherLang" time="17.267" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - no error message when question is not in english expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - no error message when question is not in english expected [true] but found [false]
at tests.ErrorHTests.QinAnotherLang(ErrorHTests.java:331)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- QinAnotherLang -->
  <testcase name="answerNotChecked" time="15.052" classname="tests.ErrorHTests"/>
  <testcase name="answersAfterLastQBack" time="44.068" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is not question 2 screen expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
This is not question 2 screen expected [true] but found [false]
at tests.ErrorHTests.answersAfterLastQBack(ErrorHTests.java:713)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- answersAfterLastQBack -->
  <testcase name="changeAnswerInSetup" time="27.183" classname="tests.ErrorHTests"/>
  <testcase name="continueWithoutAnswer" time="48.477" classname="tests.ErrorHTests"/>
  <testcase name="failedGame" time="96.634" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Correct answer is not at line 1 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Correct answer is not at line 1 expected [true] but found [false]
at tests.ErrorHTests.failedGame(ErrorHTests.java:1388)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- failedGame -->
  <testcase name="lastQback42Q" time="45.358" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is not question 2 screen expected [true] but found [false],
	This is not question 2 screen expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
This is not question 2 screen expected [true] but found [false],
This is not question 2 screen expected [true] but found [false]
at tests.ErrorHTests.lastQback42Q(ErrorHTests.java:551)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- lastQback42Q -->
  <testcase name="numberAsAnswer" time="11.48" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Answer in line 2 is not B expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Answer in line 2 is not B expected [true] but found [false]
at tests.ErrorHTests.numberAsAnswer(ErrorHTests.java:143)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- numberAsAnswer -->
  <testcase name="overMaxCharA" time="18.838" classname="tests.ErrorHTests"/>
  <testcase name="overMaxCharsQ" time="6.841" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - no error message when max characters in question is over 50 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - no error message when max characters in question is over 50 expected [true] but found [false]
at tests.ErrorHTests.overMaxCharsQ(ErrorHTests.java:103)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- overMaxCharsQ -->
  <testcase name="randomQ" time="101.357" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Questions are not random expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Questions are not random expected [true] but found [false]
at tests.ErrorHTests.randomQ(ErrorHTests.java:932)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- randomQ -->
  <testcase name="skipFillingAQuestion" time="28.555" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - A question wasn&amp;apos;t inserted expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - A question wasn't inserted expected [true] but found [false]
at tests.ErrorHTests.skipFillingAQuestion(ErrorHTests.java:301)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- skipFillingAQuestion -->
  <testcase name="selectAnswer24EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswer24EachQ -->
  <testcase name="quitAfterSetup" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- quitAfterSetup -->
  <testcase name="selectAnswer44EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswer44EachQ -->
  <testcase name="addQmarkAutomaticlly" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- addQmarkAutomaticlly -->
  <testcase name="tryAgain" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- tryAgain -->
  <testcase name="selectAnswerVar4EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswerVar4EachQ -->
  <testcase name="selectAnswer34EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswer34EachQ -->
  <testcase name="back2PrevQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- back2PrevQ -->
  <testcase name="quitGame" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- quitGame -->
</testsuite> <!-- FirefoxTest -->
